apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-archi-reservation
  labels:
    app: deployment-archi-reservation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-archi-reservation
  template:
    metadata:
      labels:
        app: deployment-archi-reservation
    spec:
      containers:
      - name: archi-reservation
        image: totank4545/archi_reservation:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-archi-reservation
spec:
  selector:
    app: service-archi-reservation
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer