apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-js-reservation-ms
  labels:
    app: deployment-js-reservation-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-js-reservation-ms
  template:
    metadata:
      labels:
        app: deployment-js-reservation-ms
    spec:
      containers:
      - name: js-reservation-ms
        image: totank4545/js-reservation-ms:v1
        ports:
        - containerPort: 3000
        imagePullPolicy : Always
---
apiVersion: v1
kind: Service
metadata:
  name: service-js-reservation-ms
spec:
  selector:
    app: service-js-reservation-ms
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer